import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./footer/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import NavTest from "./navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tour Guide App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <div>
        <NavTest />
          {children}
        <Footer />
          </div>
      </body>
    </html>
  );
}
